apiVersion: v1
kind: Service
metadata:
  name: climate-app-service
  namespace: climate-app
spec:
  selector:
    app: climate
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
  type: ClusterIP
